### ISSUE TITLE
[Android] JS Bundle fails to load with an error.

### ISSUE THREAD

**Issue by bozzmob** [iSimar/HackerNews-React-Native#13]
Hi,

I ran the following commands-

> npm install
> react-native run-anroid

The application gets deployed on my device, but, it says the server has to be running so that the app gets the JS Bundle.

I ran-

> react-native start

But, it throws up the following error-

```
root@purvotara:~/ReactJS/native/HackerNews-React-Native# react-native start
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/bozzmob/ReactJS/native/HackerNews-React-Native 


React packager ready.

 ERROR  watch /home/bozzmob/ReactJS/native/HackerNews-React-Native ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/bozzmob/ReactJS/native/HackerNews-React-Native","filename":"/home/bozzmob/ReactJS/native/HackerNews-React-Native"}
Error: watch /home/bozzmob/ReactJS/native/HackerNews-React-Native ENOSPC
    at exports._errnoException (util.js:874:11)
    at FSWatcher.start (fs.js:1239:19)
    at Object.fs.watch (fs.js:1267:11)
    at NodeWatcher.watchdir (/home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/node_modules/sane/src/node_watcher.js:45:8)
    at /home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:95:21
    at tryCallOne (/home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/home/bozzmob/ReactJS/native/HackerNews-React-Native/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)

```

What am I doing wrong?

**Comment by iSimar** [comment]
@ivanph

**Comment by ivanph** [comment]
This error seems to be coming from the packager, which is only oficially suported on OSX , you might want to check this facebook/react-native/issues/3565 and this https://facebook.github.io/react-native/docs/linux-windows-support.html#content

**Comment by bozzmob** [comment]
Thanks @ivanph and @iSimar It helped :)

**Comment by bozzmob** [comment]
Closing this issue. Got resolved.
