### ISSUE TITLE
Unable to launch app. Error listed below: 

### ISSUE THREAD

**Issue by jophyson93** [iSimar/HackerNews-React-Native#31]
Found Xcode project HN Reader.xcodeproj
Launching iPhone 6 (9.3)...
Building using "xcodebuild -project HN Reader.xcodeproj -scheme HN Reader -destination id=76AF770D-177B-4666-B40D-8D245F04D0F6 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/ios/build

xcodebuild: error: The project named "HN Reader" does not contain a scheme named "HN Reader". The "-list" option can be used to find the names of the schemes in the project.
Installing build/Build/Products/Debug-iphonesimulator/HN Reader.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HN Reader.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:469:13)
    at Object.execFileSync (child_process.js:489:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/macuser/Documents/github/Projects/Mobile/clonedProjs/HackerNews-React-Native/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/Users/macuser/.nvm/versions/node/v5.10.0/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by gareim** [comment]
Open the project file using Xcode, create a new scheme under "HN Reader" also named "HN Reader". Close Xcode, and retry running it.

**Comment by howie-misfit** [comment]
@gareim , worked for me, thanks!

**Comment by omin** [comment]
I'm getting the error even after adding a new scheme under "HN Reader". 

`$ react-native run-ios
Found Xcode project HN Reader.xcodeproj
Launching iPhone 6 (10.2)...
Building using "xcodebuild -project HN Reader.xcodeproj -scheme HN Reader -destination id=8EF4FF64-E196-4BAE-90FF-CB3735D3BB32 -derivedDataPath build"
2017-01-07 11:56:53.505 xcodebuild[80775:3508716] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-07 11:56:53.509 xcodebuild[80775:3508716] Failed to load plugin at: /Users/User/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/User/Documents/Github/HackerNews-React-Native/ios/Build

=== BUILD TARGET ActivityView OF PROJECT ActivityView WITH CONFIGURATION Debug ===

Check dependencies

** BUILD SUCCEEDED **

Installing build/Build/Products/Debug-iphonesimulator/HN Reader.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/User/Documents/Github/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HN Reader.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:465:13)
    at Object.execFileSync (child_process.js:485:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/User/Documents/Github/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/User/Documents/Github/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/User/Documents/Github/HackerNews-React-Native/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/User/Documents/Github/HackerNews-React-Native/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)`

**Comment by iiitmahesh** [comment]
@omin I have a same problem. Any solution..!

**Comment by rupalpatel0008** [comment]
I have the same problem. I have been able to fix it using following steps. Mind you this is not a solution but a workaround and its also time consuming and annoying to do. I use it as a oast resolve.

1. Delete all node modules
2. Delete your ios folder
3. Reinstall all node modules
4. Run react-native eject
4. Relink all node modules you want and reset your appdelegate, info.plist and everything in the xocode project
