### ISSUE TITLE
CFBundleIdentifier does not exist

### ISSUE THREAD

**Issue by ilyarmnzhdn** [iSimar/HackerNews-React-Native#42]
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HN Reader.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by yuguangmao** [comment]
can you post your output all?

**Comment by darrarski** [comment]
```
Found Xcode project HN Reader.xcodeproj
Launching iPhone 7 (10.3)...
Building using "xcodebuild -project HN Reader.xcodeproj -scheme HN Reader -destination id=B103EB7B-2F60-4B05-A2B1-84880C79A8ED -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/darrarski/Dev/HackerNews-React-Native/ios/build

xcodebuild: error: The project named "HN Reader" does not contain a scheme named "HN Reader". The "-list" option can be used to find the names of the schemes in the project.
Installing build/Build/Products/Debug-iphonesimulator/HN Reader.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/darrarski/Dev/HackerNews-React-Native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HN Reader.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/darrarski/Dev/HackerNews-React-Native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/darrarski/Dev/HackerNews-React-Native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/darrarski/Dev/HackerNews-React-Native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/darrarski/Dev/HackerNews-React-Native/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)
```

**Comment by yuriybash** [comment]
seeing the same problem.

**Comment by xjh1994** [comment]
+1

**Comment by cherepo** [comment]
Same problem here

**Comment by FireHsia** [comment]
change package.json 
"react": "16.0.0-alpha.6",
"react-native": "0.44.3"
delete node-modules
than  npm install

**Comment by mustafababil** [comment]
updating react-native version didn't solve :(
`$ react-native run-ios
Scanning 473 folders for symlinks in /Users/mustafababil/Development/HackerNews-React-Native/node_modules (5ms)
Found Xcode project HN Reader.xcodeproj
CoreData: annotation:  Failed to load optimized model at path '/Users/mustafababil/Downloads/Xcode-beta.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'
Launching iPhone 6 (iOS 11.0)...
Building using "xcodebuild -project HN Reader.xcodeproj -configuration Debug -scheme HN Reader -destination id=4E339365-66EB-4487-B262-25DDA787588C -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/mustafababil/Development/HackerNews-React-Native/ios/build


xcodebuild: error: The project named "HN Reader" does not contain a scheme named "HN Reader". The "-list" option can be used to find the names of the schemes in the project.

Installing build/Build/Products/Debug-iphonesimulator/HN Reader.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HN Reader.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by ihaichao** [comment]
same problem.
