### ISSUE TITLE
android version get a exception when invoke js

### ISSUE THREAD

**Issue by icefoggy** [iSimar/HackerNews-React-Native#9]
that's the log:
```
09-24 14:49:33.156    1662-1662/com.hackernews E/ViewRootImpl﹕ sendUserActionEvent() mView == null
09-24 14:49:33.196    1662-1798/com.hackernews W/ReactNativeJS﹕ 'Error: undefined is not an object (evaluating \'RCTAsyncStorage.multiMerge\')\n stack: \n  <unknown>                       index.android.bun…:45700\n  require                         index.android.bun…:254\n  <unknown>                       index.android.bun…:45067\n  require                         index.android.bun…:254\n  <unknown>                       index.android.bun…:44019\n  require                         index.android.bun…:254\n  <unknown>                       index.android.bun…:43922\n  require                         index.android.bun…:254\n  require                         index.android.bun…:200\n  __callFunction                  index.android.bun…:5612\n  <unknown>                       index.android.bun…:5559\n  guard                           index.android.bun…:5502\n  callFunctionReturnFlushedQueue  index.android.bun…:5559\n URL: http://192.168.31.8:8081/index.android.bundle?platform=android\n line: 45700\n message: undefined is not an object (evaluating \'RCTAsyncStorage.multiMerge\')'
09-24 14:49:33.196    1662-1798/com.hackernews W/ReactNativeJS﹕ 'Error: undefined is not an object (evaluating \'module[method]\')\n stack: \n  __callFunction                  index.android.bun…:5613\n  <unknown>                       index.android.bun…:5559\n  guard                           index.android.bun…:5502\n  callFunctionReturnFlushedQueue  index.android.bun…:5559\n URL: http://192.168.31.8:8081/index.android.bundle?platform=android\n line: 5613\n message: undefined is not an object (evaluating \'module[method]\')'
09-24 14:49:33.196    1662-1806/com.hackernews E/unknown:React﹕ Exception in native call from JS
    com.facebook.react.bridge.NativeArgumentsParseException: RCTNetworking.sendRequest got 2 arguments, expected 6
            at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:62)
            at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:126)
            at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
            at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:326)
            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
            at android.os.Looper.loop(Looper.java:145)
            at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by ivanph** [comment]
I did a clean build and can't reproduce this. When does this happen?

**Comment by manask88** [comment]
I get a similar error. I developed an React Native app for iOS. Then, I wanted to start doing the Android version. So, I did the following:

1. react-native android
2. react-native run-android.

And after step 2, I get a red screen in the Android emulator with similar errors

**Comment by icefoggy** [comment]
i rebuild the project, and no error happened any more. Sorry for reply slowly.

**Comment by ivanph** [comment]
Somebody else made this comment for this issue but deleted it.

>I get a similar error. I developed an React Native app for iOS. Then, I wanted to start doing the Android version. So, I did the following:
>
    react-native android
    react-native run-android.

>And after step 2, I get a red screen in the Android emulator with similar errors

Running `react-native android` generates a new android project and is not necessary. Make sure you run `npm install` to install all dependencies before running the project.
